"""initial migration

Revision ID: 045031f28450
Revises: 
Create Date: 2025-04-27 13:50:20.099434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045031f28450'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('foto_tangan_kanan', sa.String(length=255), nullable=True),
    sa.Column('foto_tangan_kiri', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nim'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mata_kuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.String(length=20), nullable=False),
    sa.Column('nama_mk', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('tahun_akademik', sa.String(length=4), nullable=False),
    sa.Column('kelas', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_mk')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jadwal_perkuliahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mata_kuliah_id', sa.Integer(), nullable=False),
    sa.Column('pertemuan_ke', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kontrak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_nim', sa.String(length=20), nullable=False),
    sa.Column('mata_kuliah_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mahasiswa_nim'], ['mahasiswa.nim'], ),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kehadiran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_nim', sa.String(length=20), nullable=False),
    sa.Column('jadwal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('waktu_scan', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jadwal_id'], ['jadwal_perkuliahan.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_nim'], ['mahasiswa.nim'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kehadiran')
    op.drop_table('kontrak')
    op.drop_table('jadwal_perkuliahan')
    op.drop_table('users')
    op.drop_table('mata_kuliah')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
