"""User1

Revision ID: 53f2a221d232
Revises: 30b0aa112c3e
Create Date: 2025-04-27 01:57:00.746977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f2a221d232'
down_revision: Union[str, None] = '30b0aa112c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
