"""mhs1

Revision ID: d2dc78aeffd5
Revises: eaf3ebd92220
Create Date: 2025-04-27 02:06:46.645306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2dc78aeffd5'
down_revision: Union[str, None] = 'eaf3ebd92220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('foto_tangan_kiri', sa.String(length=200), nullable=True),
    sa.Column('foto_tangan_kanan', sa.String(length=200), nullable=True),
    sa.Column('foto_wajah', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('nim')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
